# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Easy Recipeasy Alpha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Easy Recipeasy Alpha
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'Easy Recipeasy AlphaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Easy Recipeasy AlphaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
